
CREATE DATABASE IF NOT EXISTS TEST;
USE TEST;
 CREATE TABLE IF NOT EXISTS USERS(
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(100),
    NICKNAME VARCHAR(20),
    EMAIL VARCHAR(50),
    PASSWORD VARCHAR(16),
    PRIMARY KEY(ID)
);